robomuse_diff:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'chassis_to_left_wheel'
  right_wheel : 'chassis_to_right_wheel'
  publish_rate: 10.0  # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.435 # meters
  wheel_radius : 0.062105 # meters

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1 #0.9655  # default: 1.0
  wheel_radius_multiplier    : 1 #.0737 # default: 1.0
  
  
  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_link 

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.75 
      has_acceleration_limits: true
      max_acceleration       : 0.05 
      has_jerk_limits        : true
      max_jerk               : 0.05 
 
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.75 #1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.05  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 0.05  # rad/s^3

#Publish to TF directly or not
enable_odom_tf: false

#Name of frame to publish odometry in
odom_frame_id: encoder_odom

# Publish the velocity command to be executed.
# It is to monitor the effect of limiters on the controller input.
publish_cmd: true
