# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
#-
#  name    : navigation
#  topic   : nav_vel
#  timeout : 0.5
#  priority: 10
#-
#  name    : joystick
#  topic   : joy_vel
#  timeout : 0.5
#  priority: 100
#-
#  name    : keyboard
#  topic   : key_vel
#  timeout : 0.5
#  priority: 90
#-
#  name    : tablet
#  topic   : tab_vel
#  timeout : 0.5
#  priority: 100

-
  name    : human_detected
  topic   : human_stop/cmd_vel
  timeout : 0.5
  priority: 190
-
  name    : keyboard
  topic   : keyboard/cmd_vel
  timeout : 0.5
  priority: 120
-
  name    : ps3 node
  topic   : ps3/cmd_vel
  timeout : 0.5
  priority: 150
-
  name    : move_base
  topic   : navigation/cmd_vel
  timeout : 0.5
  priority: 100
#-
#  name    : obstacle detection node
#  topic   : obstacle/cmd_vel
#  timeout : 0.5
#  priority: 200
